apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
      - name: swiggy
        image: swiggy-app
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: swiggy-service
spec:
  type: NodePort
  selector:
    app: swiggy
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
